/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpart;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class addquestions extends javax.swing.JFrame {

    /**
     * Creates new form addquestions
     */
    public addquestions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        category = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        Option_a = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Option_b = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Option_c = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Option_d = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        correct_answer = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question.setText("QUESTION:->");
        jPanel1.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 68, 80, 38));

        jButton1.setText("Add question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 107, 32));

        category.setText("CATEGORY");
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 33, 90, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Aptitude", "Operating System", "DBMS", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 30, 120, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, 331, 29));

        Option_a.setText("A");
        jPanel1.add(Option_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 154, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 151, 129, -1));

        Option_b.setText("B");
        jPanel1.add(Option_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 192, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 189, 129, -1));

        Option_c.setText("C");
        jPanel1.add(Option_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 230, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 227, 129, -1));

        Option_d.setText("D");
        jPanel1.add(Option_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 261, -1, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 258, 129, -1));

        correct_answer.setText("CORRECT ANSWER");
        jPanel1.add(correct_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 287, 100, 20));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 284, 173, -1));

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 363, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


            String ques=jTextField1.getText();
            String op1=jTextField2.getText();
            String op2=jTextField3.getText();
            String op3=jTextField4.getText();
            String op4=jTextField5.getText();
            String correct=jTextField6.getText();
            String category=(String)jComboBox1.getSelectedItem();
            
            if(ques.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Question field cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (op1.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Option field cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (op2.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Option field cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (op3.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Option field cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (op4.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Option field cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (correct.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, " Enter the correct Answer","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if (category.equalsIgnoreCase("Select Category"))
            {
                JOptionPane.showMessageDialog(rootPane, "Please!! Select the Category of the question...","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
            
                            try{
                                        Connection con=dbconnection.dbconnect.getConnection();

                                        PreparedStatement ps=con.prepareStatement("insert into questions values(?,?,?,?,?,?,?)");
                                        ps.setString(1, ques);
                                        ps.setString(2, op1);
                                        ps.setString(3, op2);
                                        ps.setString(4, op3);
                                        ps.setString(5, op4);
                                        ps.setString(6, correct);
                                        ps.setString(7, category);

                                        int  i=ps.executeUpdate();
                                        if(i>0)
                                        {
                                            JOptionPane.showMessageDialog(rootPane, "Question added succesfully");
                                            jTextField1.setText("");
                                            jTextField2.setText("");
                                            jTextField3.setText("");
                                            jTextField4.setText("");
                                            jTextField5.setText("");
                                            jTextField6.setText("");
                                            jComboBox1.setSelectedIndex(0);
                                        }          
                            }
                            catch(Exception ex)
                            {
                                System.out.println(ex);
                            }}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        adminprofile ap=new adminprofile(null);
        ap.setVisible(true);
        setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addquestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Option_a;
    private javax.swing.JLabel Option_b;
    private javax.swing.JLabel Option_c;
    private javax.swing.JLabel Option_d;
    private javax.swing.JLabel Question;
    private javax.swing.JLabel category;
    private javax.swing.JLabel correct_answer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
